# 大文字と小文字を区別するため注意して定義してください
# ------------------------------------------------------------
# Head部,Body部取得のためのXpath
# ------------------------------------------------------------
xml_head: "/WarningReport/Summary"
xml_body: "/WarningReport/Detail/Text"

# ------------------------------------------------------------
# Issuesテーブルの拡張フィールド用定義(河川XML用)
# key:カラム名 value:XML内から要素取得のためのXpath
# ------------------------------------------------------------
issue_extras: 
# 要因(WarningReport@cause)
 "xml_control_cause": "/WarningReport/@cause"
# 承認(WarningReport@apply)
 "xml_control_apply": "/WarningReport/@apply"
# 題名(Name)
 "subject": "/WarningReport/Summary/ReportKind/Name/text()"

# ------------------------------------------------------------
# トラッカー用定義
# 河川のトラッカーIDは固定
# ------------------------------------------------------------
tracker: "6"

# ------------------------------------------------------------
# プロジェクト用定義
# ------------------------------------------------------------
projects: 
 path: "/WarningReport/@cause"
 type: 
  "0": "I04202000000000000002"
  "1": "I04202000000000000002"
  "2": "I04202000000000000002"
  "3": "I04202000000000000002"
 default: "I04202000000000000002"
