file_monitor:
 host: "mx5.di-system.co.jp"
 port: "25"
 from:
  address: "pjhv6wmvxiej2w8z0mpk@docomo.ne.jp"
  display_name: "Akira Tsutsumi"
 to:
  - address: "atsutsumi@di-system.co.jp"
    display_name: "Akira Tsutsumi"
  - address: "pjhv6wmvxiej2w8z0mpk@docomo.ne.jp"
    display_name: "名無しの権兵衛"
 cc:
 bcc:
 subject: "[ERROR NOTIFICATION (FILE MONITOR)]"
 body:  
  "An error has occurred in the file monitoring program.\nThe error is the following:\n\n$1"
