# ----------------------------------------------------------
# Configuration file for log4r
# ----------------------------------------------------------

log4r_config:
  
 loggers:
  - name: "Server"
    type: "Logger"
    level: "DEBUG"
    trace: "true"
    outputters:
     - "StdOut"
     - "F1"
  - name: "Parser"
    type: "Logger"
    level: "DEBUG"
    trace: "true"
    outputters:
     - "StdOut"
     - "F2"
  
 outputters:
  - name: "StdOut"
    type: "StdoutOutputter"
    level: "DEBUG"
    formatter:
     name: "P1"
     type: "PatternFormatter"
     pattern: "%d [%l] %m"
     date_pattern: "%H:%M:%S"
  - name: "F1"
    type: "DateFileOutputter"
    date_pattern: "%Y%m%d"
    dirname: "/home/mrsuser/MRS/socket-server/log"
    trunc: "false"
    formatter:
     name: "P2"
     type: "PatternFormatter"
     pattern: "%d [%l] %C(%t) - %M"
     date_pattern: "%Y/%m/%d %H:%M:%S"
  - name: "F2"
    type: "DateFileOutputter"
    date_pattern: "%Y%m%d"
    dirname: "/home/mrsuser/MRS/socket-server/log"
    trunc: "false"
    formatter:
     name: "P3"
     type: "PatternFormatter"
     pattern: "%d [%l] %C(%t) - %M"
     date_pattern: "%Y/%m/%d %H:%M:%S"
